### ISSUE TITLE
Just won't start

### ISSUE THREAD

**Issue by Samuel-Kowatschek** [Sanjit1/hillClimbRacing#1]
So I tried the original version of code bullet and everything worked just perfectly fine, but now I wanted to try your version as well. But here nothing starts, even if I choose a character, nothing happens.

**Comment by Sanjit1** [comment]
Yo, how did you attempt to run the code?

**Comment by Samuel-Kowatschek** [comment]
I opened the index.html and then tried to press one of the buttons. Seems like buttons don't work at all, because if I go into the specific html files the program works.

**Comment by Sanjit1** [comment]
hmmm, these buttons are a result of me being so bad at Html and css. If you click directly on the underlined text and i should work
![yo](https://user-images.githubusercontent.com/26168871/54574454-9fc26d80-49ad-11e9-9cf8-c11b96d0fe79.PNG)

**Comment by Sanjit1** [comment]
Also just curious, how did you find this repo?

**Comment by Sanjit1** [comment]
Did it work?

**Comment by Sanjit1** [comment]
In that case, I shall close the issue.
